### ISSUE TITLE
java.lang.StackOverflowError when processing

### ISSUE THREAD

**Issue by andaag** [bluelinelabs/LoganSquare#12]
Hi

I just stuck @JsonObject/@JsonField on a .. ton of classes, and compiling now I get:

```
error: Exception while processing Json classes. Stack trace incoming:
  java.lang.StackOverflowError
  	at com.squareup.javapoet.ClassName.<init>(ClassName.java:43)
  	at com.squareup.javapoet.ClassName.get(ClassName.java:165)
  	at com.squareup.javapoet.TypeName$1.visitDeclared(TypeName.java:132)
  	at com.squareup.javapoet.TypeName$1.visitDeclared(TypeName.java:107)
  	at com.sun.tools.javac.code.Type$ClassType.accept(Type.java:936)
  	at com.squareup.javapoet.TypeName.get(TypeName.java:107)
  	at com.squareup.javapoet.TypeVariableName.get(TypeVariableName.java:88)
  	at com.squareup.javapoet.TypeName$1.visitTypeVariable(TypeName.java:147)
  	at com.squareup.javapoet.TypeName$1.visitTypeVariable(TypeName.java:107)
  	at com.sun.tools.javac.code.Type$TypeVar.accept(Type.java:1319)
  	at com.squareup.javapoet.TypeName.get(TypeName.java:107)
  	at com.squareup.javapoet.TypeName$1.visitDeclared(TypeName.java:137)
  	at com.squareup.javapoet.TypeName$1.visitDeclared(TypeName.java:107)
  	at com.sun.tools.javac.code.Type$ClassType.accept(Type.java:936)
  	at com.squareup.javapoet.TypeName.get(TypeName.java:107)
  	at com.squareup.javapoet.TypeVariableName.get(TypeVariableName.java:88)
  	at com.squareup.javapoet.TypeName$1.visitTypeVariable(TypeName.java:147)
  	at com.squareup.javapoet.TypeName$1.visitTypeVariable(TypeName.java:107)
  	at com.sun.tools.javac.code.Type$TypeVar.accept(Type.java:1319)
```
And so on... Now it wouldn't surprise me if the problem exists in my code, consider this bug report a bug report on the not so helpful error message. Maybe some debug mode can be supported that prints out which classes it's currently working on?

**Comment by andaag** [comment]
PEBCAK, the error was above the stackoverflow.

**Comment by andaag** [comment]
Another PEBCAK, my dummy logging produced logging that looked like a proper error message ;). So I'd still want some better logging in there!

**Comment by EricKuck** [comment]
Error messages are definitely a weak point at the moment. It looks like you fixed your specific issue, so I'll close this one and have reopened another, more general, issue about handling errors better: https://github.com/bluelinelabs/LoganSquare/issues/15. If you could provide some info about what your issue ended up being, I'll make sure there's better error messaging there.

**Comment by andaag** [comment]
My problem was trying to use @JsonObject with an abstract parent using generics. Not really that surprised that it failed ;)

**Comment by EricKuck** [comment]
Ah, makes sense. I'll get some error handling in there for that one. Thanks!
