### ISSUE TITLE
simple custom StringBasedTypeConverter produces "Can not write a field name, expecting a value"

### ISSUE THREAD

**Issue by andaag** [bluelinelabs/LoganSquare#14]
I get this when serializing something with a custom simple typeconverter:

```
     Caused by: com.fasterxml.jackson.core.JsonGenerationException: Can not write a field name, expecting a value
            at com.fasterxml.jackson.core.JsonGenerator._reportError(JsonGenerator.java:1574)
            at com.fasterxml.jackson.core.json.WriterBasedJsonGenerator.writeFieldName(WriterBasedJsonGenerator.java:102)
            at com.fasterxml.jackson.core.json.JsonGeneratorImpl.writeStringField(JsonGeneratorImpl.java:169)
            at com.bluelinelabs.logansquare.typeconverters.StringBasedTypeConverter.serialize(StringBasedTypeConverter.java:31)
            at no.finn.android.ui.objectpage.ObjectPageContainerScreen$$JsonObjectMapper._serialize(ObjectPageContainerScreen$$JsonObjectMapper.java:70)
            at no.finn.android.ui.objectpage.ObjectPageContainerScreen$$JsonObjectMapper.serialize(ObjectPageContainerScreen$$JsonObjectMapper.java:59)
            at no.finn.android.ui.objectpage.ObjectPageContainerScreen$$JsonObjectMapper.serialize(ObjectPageContainerScreen$$JsonObjectMapper.java:14)
```

Looking at the code:
```
    if (object.searchUrl != null) {
      jsonGenerator.writeFieldName("searchUrl");
      FINN_URL_CONVERTER.serialize(object.searchUrl, "searchUrl", jsonGenerator);
    }
```
This seems wrong, as serialize itself calls jsonGenerator.writeStringField(fieldName, convertToString(object));

**Comment by EricKuck** [comment]
Nice catch. This will be fixed shortly.

**Comment by EricKuck** [comment]
Version 1.0.3 fixes this issue. If you update the version number of both the compiler and runtime in your build.gradle, you should be good to go.

**Comment by andaag** [comment]
:+1: thanks :)
