### ISSUE TITLE
NoSuchMapperException in a derived class

### ISSUE THREAD

**Issue by alfdev** [bluelinelabs/LoganSquare#156]
Hi,

i have this model:

```
@JsonObject
public class ValidationErrorsModel {

    @SerializedName("validation_errors")
    @JsonField(name = "validation_errors")
    public SimpleArrayMap<String, List<String>> validationErrors;
}
```

and i have another one that extends it:

```
@JsonObject
public class UserCreateModel extends ValidationErrorsModel 
```

but it appears this error:

```
Caused by: com.bluelinelabs.logansquare.NoSuchMapperException: Class io.swagger.client.model.ValidationErrorsModel could not be mapped to a JSON object. Perhaps it hasn't been annotated with @JsonObject?
                                                                         at com.bluelinelabs.logansquare.LoganSquare.mapperFor(LoganSquare.java:304)
                                                                         at io.swagger.client.model.UserCreateModel$$JsonObjectMapper.<clinit>(UserCreateModel$$JsonObjectMapper.java:15)
```

any idea how can i solve it?

Thanks

**Comment by EricKuck** [comment]
I haven't been able to reproduce anything like this since you submitted the issue. Would it be possible to create a small demo so I could check out what's going wrong?

**Comment by alfdev** [comment]
Hi Eric,

i've build a project that reproduce the issue:
[https://github.com/alfdev/DemoIssueLogansquare](https://github.com/alfdev/DemoIssueLogansquare)

Thank you.
