### ISSUE TITLE
ArrayIndexOutOfBoundsException in SimpleArrayMap while registering type converter

### ISSUE THREAD

**Issue by kunjan-a** [bluelinelabs/LoganSquare#188]
While using LoganSquare (v1.3.7) for parsing json strings into java Pojos, some times I get a crash while registering type converter.
Corresponding stack trace is:
`Caused by java.lang.ArrayIndexOutOfBoundsException: src.length=8 srcPos=0 dst.length=8 dstPos=2 length=8
       at java.lang.System.arraycopy(System.java)
       at com.bluelinelabs.logansquare.util.SimpleArrayMap.put(SimpleArrayMap.java:400)
       at com.bluelinelabs.logansquare.LoganSquare.registerTypeConverter(LoganSquare.java:350)`

Is this issue known or has it been fixed already?

Please do let me know if I can provide some other information.

**Comment by ericleong** [comment]
As far as I can tell, the [implementation of `SimpleArrayMap.java` in LoganSquare](https://github.com/bluelinelabs/LoganSquare/blob/development/core/src/main/java/com/bluelinelabs/logansquare/util/SimpleArrayMap.java) is the same as the [implementation in the support library](https://android.googlesource.com/platform/frameworks/support/+/refs/heads/master/compat/java/android/support/v4/util/SimpleArrayMap.java), except LoganSquare has:

* the debug statements removed
* a simpler `equals()` implementation that doesn't check for `SimpleArrayMap`
* a different lock object (`SimpleArrayMap.class` instead of `ArrayMap.class`)

The `binarySearch()` method is in a different place but the implementation looks identical. It may really be a bug in `SimpleArrayMap` - here's [a crash caused by the same bug in the Android support library](https://issuetracker.google.com/issues/37006016). But since it happens intermittently I'm inclined to think it's a race condition.

**Comment by nateridderman** [comment]
I'm also seeing this issue in my app intermittently.

**Comment by nateridderman** [comment]
I believe the issue is that `LoganSquare.registerTypeConverter()` is not thread safe. My app was calling it in multiple places, possibly at the same time from different threads. I noticed that they are stored in `TYPE_CONVERTER` which is a static final field. Seems bad. I'll try to follow up once my app is fixed to see if the crash reports disappear.
