### ISSUE TITLE
Is this can be used in Java Project?

### ISSUE THREAD

**Issue by zsigui** [bluelinelabs/LoganSquare#46]
Hello, I want to know the answer about that question : Is this can be used in Java Project? I tried to pack it to .jar and used in a java project, but unfortunaly it failed and i get the exception as Follow:
```
Exception in thread "main" com.bluelinelabs.logansquare.NoSuchMapperException: Class User could not be mapped to a JSON object. Perhaps it hasn't been annotated with @JsonObject?
	at com.bluelinelabs.logansquare.LoganSquare.mapperFor(LoganSquare.java:171)
	at com.bluelinelabs.logansquare.LoganSquare.serialize(LoganSquare.java:100)
	at JsonTest.main(JsonTest.java:14)
Caused by: java.lang.ClassNotFoundException: User$$JsonObjectMapper
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at com.bluelinelabs.logansquare.LoganSquare.mapperFor(LoganSquare.java:167)
	... 2 more
```
Can't it provide in java project? Or i worked in bad way?

**Comment by EricKuck** [comment]
There's no reason this wouldn't work with standard Java projects, but they're not supported at all, since this library was intended for Android. If you've annotated your User object with `@JsonObject`, then my guess is that the `JsonObjectMapper` class either isn't being generated or isn't being included in your jar for some reason. If you're using a build system other than Gradle, you'll probably have to figure out how to get the annotation processor to run.
