### ISSUE TITLE
NoSuchMapperException

### ISSUE THREAD

**Issue by myalban** [bluelinelabs/LoganSquare#54]
Hi,

I 've just discovered this library and want to rewrite my code to avoid usin the Gson .

But I got this error

03-23 18:36:20.532    2071-2092/u.a D/A [com.u.Networks.Http.Requests.RequestGson]﹕ [
    {
    "table": "glycemies",
    "version": 2
    }
    ]
03-23 18:36:20.544    2071-2092/u.a W/dalvikvm﹕ dvmFindClassByName rejecting '[Lu.a.Api.Models.ModelSyncTableStatus;$$JsonObjectMapper'
03-23 18:36:20.552    2071-2092/u.a E/Volley﹕ [109] NetworkDispatcher.run: Unhandled exception com.bluelinelabs.logansquare.NoSuchMapperException: Class u.a.Api.Models.ModelSyncTableStatus[] could not be mapped to a JSON object. Perhaps it hasn't been annotated with @JsonObject?
    com.bluelinelabs.logansquare.NoSuchMapperException: Class u.a.Api.Models.ModelSyncTableStatus[] could not be mapped to a JSON object. Perhaps it hasn't been annotated with @JsonObject?
            at com.bluelinelabs.logansquare.LoganSquare.mapperFor(LoganSquare.java:171)
            at com.bluelinelabs.logansquare.LoganSquare.parse(LoganSquare.java:50)
            at com.u.Networks.Http.Requests.RequestGson.parseNetworkResponse(RequestGson.java:155)
            at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:123)
     Caused by: java.lang.ClassNotFoundException: [Lu.a.Api.Models.ModelSyncTableStatus;$$JsonObjectMapper
            at java.lang.Class.classForName(Native Method)
            at java.lang.Class.forName(Class.java:217)
            at java.lang.Class.forName(Class.java:172)
            at com.bluelinelabs.logansquare.LoganSquare.mapperFor(LoganSquare.java:167)
            at com.bluelinelabs.logansquare.LoganSquare.parse(LoganSquare.java:50)
            at com.u.Networks.Http.Requests.RequestGson.parseNetworkResponse(RequestGson.java:155)
            at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:123)
03-23 18:36:20.844    2071-2096/u.a I/A [u.a.Syncronisation.SyncAdapter]﹕ WTF: java.util.concurrent.ExecutionException: com.android.volley.VolleyError: com.bluelinelabs.logansquare.NoSuchMapperException: Class u.a.Api.Models.ModelSyncTableStatus[] could not be mapped to a JSON object. Perhaps it hasn't been annotated with @JsonObject?

Then my class is like this : 

package u.a.Api.Models;

import com.bluelinelabs.logansquare.annotation.JsonField;
import com.bluelinelabs.logansquare.annotation.JsonObject;
//import com.google.gson.annotations.Expose;
//import com.google.gson.annotations.SerializedName;
@JsonObject
public class ModelSyncTableStatus {
    @JsonField
    public String table;
    @JsonField
    public int version;

Can you help me ?

**Comment by EricKuck** [comment]
You have a JSON array, not a JSON object. If you use `LoganSquare.parseArray()` instead of `LoganSquare.parse()` you should get exactly what you want.

**Comment by RahulHawge** [comment]
Hi, I am using
ErrorResponse[] error_response = LoganSquare.parse(errorResponse,ErrorResponse[].class);
but as you suggested, i tried using,
ErrorResponse[] error_response = LoganSquare.parseArray(errorResponse,ErrorResponse[].class);
But it say "canot resolve method parseArray".
what shuold i do?

**Comment by EricKuck** [comment]
Sorry, not sure why I said `parseArray` before. It's `parseList`.
