### ISSUE TITLE
DexException when adding the library to build.gradle

### ISSUE THREAD

**Issue by lancelebanoff** [bluelinelabs/LoganSquare#55]
Hi. I added LoganSquare to my app's build.gradle file as described in the Download section on your main Github page. When I build my project, the build fails and I get this error:

```
UNEXPECTED TOP-LEVEL EXCEPTION:
com.android.dex.DexException: Multiple dex files define Lcom/fasterxml/jackson/core/Base64Variant;
        at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:594)
        at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:552)
        at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:533)
        at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:170)
        at com.android.dx.merge.DexMerger.merge(DexMerger.java:188)
        at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:439)
        at com.android.dx.command.dexer.Main.runMonoDex(Main.java:287)
        at com.android.dx.command.dexer.Main.run(Main.java:230)
        at com.android.dx.command.dexer.Main.main(Main.java:199)
        at com.android.dx.command.Main.main(Main.java:103)
```

Here's my list of dependencies in my build.gradle file:

```
dependencies {
    compile 'com.bluelinelabs:logansquare-compiler:1.0.6'
    compile 'com.bluelinelabs:logansquare:1.0.6'
    compile 'com.android.support:support-v4:18.0.+'
    compile 'com.android.support:appcompat-v7:18.0.+'
    compile 'com.viewpagerindicator:library:2.4.2-SNAPSHOT'
    compile 'com.commonsware.cwac:merge:1.0.1'
    compile files('libs/libGoogleAnalyticsV2.jar')
    compile files('libs/aws-android-sdk-2.1.1-core.jar')
    compile files('libs/aws-android-sdk-2.1.1-s3.jar')
    compile('com.crashlytics.sdk.android:crashlytics:2.0.1@aar') {
        transitive = true;
    }
```

**Comment by talklittle** [comment]
@lancelebanoff That's not quite right. The docs tell you to add the `apt` build step and **add** the dependency:

    apt 'com.bluelinelabs:logansquare-compiler:1.0.6'

You should **remove**

    compile 'com.bluelinelabs:logansquare-compiler:1.0.6'

**Comment by EricKuck** [comment]
Nice catch @talklittle. I'd been trying to figure out what the issue was for a while...totally skipped right over that line. Thanks!
