### ISSUE TITLE
NoSuchMapperException even though class is annotated with @JsonObject

### ISSUE THREAD

**Issue by ravikumar-n** [bluelinelabs/LoganSquare#62]
I'd tried to create [LoganSquareConverter](https://github.com/ravikumar-n/retrofit/tree/master/retrofit-converters/logansquare) for Retrofit. But I'm facing with `NoSuchMapperException` when I run the project, even though `MyObject` class is annotated. Can you help me solving the issue?
  
```
com.bluelinelabs.logansquare.NoSuchMapperException: Class retrofit.converter.MyObject could not be mapped to a JSON object. Perhaps it hasn't been annotated with @JsonObject?com.bluelinelabs.logansquare.NoSuchMapperException: Class retrofit.converter.MyObject could not be mapped to a JSON object. Perhaps it hasn't been annotated with @JsonObject?
	at com.bluelinelabs.logansquare.LoganSquare.mapperFor(LoganSquare.java:171)
	at com.bluelinelabs.logansquare.LoganSquare.serialize(LoganSquare.java:100)
	at retrofit.converter.LoganSquareConverter.toBody(LoganSquareConverter.java:36)
	at retrofit.converter.LoganSquareConverterTest.serialize(LoganSquareConverterTest.java:25)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.junit.runners.Suite.runChild(Suite.java:127)
	at org.junit.runners.Suite.runChild(Suite.java:26)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:78)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:212)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
Caused by: java.lang.ClassNotFoundException: retrofit.converter.MyObject$$JsonObjectMapper
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:191)
	at com.bluelinelabs.logansquare.LoganSquare.mapperFor(LoganSquare.java:167)
	... 37 more
```

**Comment by EricKuck** [comment]
Can you post your build.gradle file? My guess is that the apt line is missing, but without more information I can't really tell for sure.

**Comment by ravikumar-n** [comment]
@EricKuck RetroFit uses maven as build tool (I'm newbie to Maven), I'm not sure If I'm missing some configuration related to LoganSquare especially `android-apt`.

**Comment by EricKuck** [comment]
Unfortunately I'm on the road and can't test this too much, but I'm pretty sure you can fix this by adding this dependency in your .pom file:

```
        <dependency>
            <groupId>com.bluelinelabs</groupId>
            <artifactId>logansquare-compiler</artifactId>
            <version>${logansquare.version}</version>
        </dependency>
```

The annotation processor and core library are two different artifacts, since with gradle you have to declare the `apt` and `compile` commands separately anyway. Let me know if that doesn't work and I'll try to take a look when I get back to a computer sometime tomorrow.

**Comment by ravikumar-n** [comment]
Adding `logansquare-compiler` and `JavaPoet` to .pom file fixed the issue. 
```
        <dependency>
            <groupId>com.squareup</groupId>
            <artifactId>javapoet</artifactId>
            <version>1.0.0</version>
        </dependency>
```
Thanks Eric.

**Comment by EricKuck** [comment]
Sweet! Thanks for writing a proper Retrofit adapter too.
