### ISSUE TITLE
Annotated Object Array does not work.

### ISSUE THREAD

**Issue by gencube** [bluelinelabs/LoganSquare#66]
Hi, 

This error was met while serializing **Person Array**:
```java
Cannot convert to JSON:[Lmi.ram.models.Person;@71662a45
com.bluelinelabs.logansquare.NoSuchMapperException: Class mi.ram.models.Person[] could not be mapped to a JSON object. Perhaps it hasn't been annotated with @JsonObject?
	at com.bluelinelabs.logansquare.LoganSquare.mapperFor(LoganSquare.java:171)
	at com.bluelinelabs.logansquare.LoganSquare.serialize(LoganSquare.java:100)
	at mi.netty4.utils.LoganJsonUtils.toJson(LoganJsonUtils.java:21)
	at mi.netty4.utils.LoganJsonUtils.toJsonBytes(LoganJsonUtils.java:16)
```
I have annotated the person class like such:

```java
@JsonObject
@XmlRootElement(name = "Person")
public class Person {
    @JsonField
    private String pid;
    @JsonField
    private String name;
    @JsonField
    private boolean isMale = false;
    @JsonField
    private Date dob;
... // setter getters
}
....
public static String toJson(Object data) {
        try {
            return LoganSquare.serialize(data);
        } catch (Exception ex) {
            log.error("Cannot convert to JSON:" + data, ex);
            return EMPTY_JSON;
        } finally {
            System.gc();
        }
}

Person[] persons={new Person(...), new Person(...), new Person(...)};
String json= toJson(persons);
```
**How to overcome this issue?**

**Comment by EricKuck** [comment]
Can you post your build.gradle file? My guess is that you're missing this line: `apt 'com.bluelinelabs:logansquare-compiler:1.1.0'`

**Comment by KimiChiu** [comment]
I have the same problem.

```
apt 'com.bluelinelabs:logansquare-compiler:1.3.6'
compile 'com.bluelinelabs:logansquare:1.3.6'
```
```
Person[][] persons = new new Person[30][30];
// NoSuchMapperException
LoganSquare.serialize(persons);
// NoSuchMapperException
LoganSquare.serialize(persons[0]);
// Success
LoganSquare.serialize(persons[0][0]);
```
Any ideas?
