### ISSUE TITLE
Conflict with Dagger

### ISSUE THREAD

**Issue by ffelini** [bluelinelabs/LoganSquare#83]
Hi. I'm using Dagger in my project. http://square.github.io/dagger/
After connecting LoganSquare to the project I'm getting strange errors that I'm not getting without it.

They both use annotation processors so maybe it is cause of some conflicts in between?

Caused by: java.lang.IllegalStateException: Module adapter for class com.namshi.android.injection.modules.ApplicationScopeModule could not be loaded. Please ensure that code generation was run for this module.
            at dagger.internal.FailoverLoader$1.create(FailoverLoader.java:45)
            at dagger.internal.FailoverLoader$1.create(FailoverLoader.java:40)
            at dagger.internal.Memoizer.get(Memoizer.java:56)
            at dagger.internal.FailoverLoader.getModuleAdapter(FailoverLoader.java:57)
            at dagger.internal.Modules.loadModules(Modules.java:43)
            at dagger.ObjectGraph$DaggerObjectGraph.makeGraph(ObjectGraph.java:174)
            at dagger.ObjectGraph$DaggerObjectGraph.access$000(ObjectGraph.java:138)
            at dagger.ObjectGraph.create(ObjectGraph.java:129)

**Comment by ffelini** [comment]
For those who will encounter this issue here is the solution.
Just don't forget to set dagger annotation processor.

    apt 'com.squareup.dagger:dagger-compiler:1.2.2'
