### ISSUE TITLE
List of Enums causes invalid Json during serialization or crashes during parse

### ISSUE THREAD

**Issue by awenger** [bluelinelabs/LoganSquare#90]
Model:
```java
@JsonObject
public class LsTest {
    @JsonField
    String test;
    @JsonField(name = "enum_test")
    LsEnumTest enumTest;
    @JsonField(name = "enum_list")
    List<LsEnumTest> enumList = new ArrayList<>();

    public String getTest() {
        return test;
    }

    public LsEnumTest getEnumTest() {
        return enumTest;
    }

    public List<LsEnumTest> getEnumList() {
        return enumList;
    }
}
```
```java
public enum LsEnumTest {
    ONE, TWO
}
```
converter
```java
public class LsEnumTestConverter extends StringBasedTypeConverter<LsEnumTest> {
    @Override
    public LsEnumTest getFromString(String string) {
       return LsEnumTest.valueOf(string);
    }

    @Override
    public String convertToString(LsEnumTest lsEnumTest) {
        return lsEnumTest.toString();
    }
}
```
parse/serialize
```java
try {
    //String raw = "{\"test\":\"test\",\"enum_test\":\"ONE\",\"enum_list\":[\"ONE\"]}"; // invalid json after serialize
    String raw = "{\"test\":\"test\",\"enum_test\":\"ONE\",\"enum_list\":[\"ONE\",\"TWO\"]}"; // crash during parse
    LoganSquare.registerTypeConverter(LsEnumTest.class, new LsEnumTestConverter());
    LsTest test = LoganSquare.parse(raw, LsTest.class);
    Log.d("test", "test: " + test.getTest());
    Log.d("test", "enumTest: " + test.getEnumTest());
    List<LsEnumTest> list = test.getEnumList();
    for (LsEnumTest entry : list) {
        Log.d("test", "enumList contains: " + entry);
    }
    String serialized = LoganSquare.serialize(test);
    Log.d("test", "serialized: " + serialized);
} catch (IOException e) {
    e.printStackTrace();
}
```
json string with >2 elements in the enum_list property:
```java
D/test﹕ test: test
D/test﹕ enumTest: ONE
D/test﹕ enumList contains: ONE
D/test﹕ enumList contains: TWO
W/System.err﹕ com.fasterxml.jackson.core.JsonGenerationException: Can not write a field name, expecting a value
W/System.err﹕ at com.fasterxml.jackson.core.JsonGenerator._reportError(JsonGenerator.java:1649)
W/System.err﹕ at com.fasterxml.jackson.core.json.WriterBasedJsonGenerator.writeFieldName(WriterBasedJsonGenerator.java:109)
W/System.err﹕ at com.fasterxml.jackson.core.json.JsonGeneratorImpl.writeStringField(JsonGeneratorImpl.java:168)
W/System.err﹕ at com.bluelinelabs.logansquare.typeconverters.StringBasedTypeConverter.serialize(StringBasedTypeConverter.java:31)
W/System.err﹕ at ....LsTest$$JsonObjectMapper._serialize(LsTest$$JsonObjectMapper.java:75)
W/System.err﹕ at ....LsTest$$JsonObjectMapper.serialize(LsTest$$JsonObjectMapper.java:62)
W/System.err﹕ at ....LsTest$$JsonObjectMapper.serialize(LsTest$$JsonObjectMapper.java:15)
W/System.err﹕ at com.bluelinelabs.logansquare.JsonMapper.serialize(JsonMapper.java:209)
```
json string with 1 element (invalid json after serialization):
```java
D/test﹕ test: test
D/test﹕ enumTest: ONE
D/test﹕ enumList contains: ONE
D/test﹕ serialized: {"enum_list":["lslocalenum_listElement""ONE"],"enum_test":"ONE","test":"test"}
```

**Comment by EricKuck** [comment]
Sorry about the long wait! This has now been fixed in v1.2.6.
